// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FirstLayer: typeof import('./src/components/FirstLayer.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RegisterBar: typeof import('./src/components/RegisterBar.vue')['default']
    RegisterBL: typeof import('./src/components/RegisterBL.vue')['default']
    RegisterBR: typeof import('./src/components/RegisterBR.vue')['default']
    RegisterTL: typeof import('./src/components/RegisterTL.vue')['default']
    RegisterTR: typeof import('./src/components/RegisterTR.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
